# Generated by Django 5.1.6 on 2025-02-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_portfolioitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
