# Generated by Django 5.1.6 on 2025-02-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
